#!/usr/bin/env python3
from pathlib import Path
import re

# The old EC2 history concept is gone. These remaining identifiers were unrelated
# local counters/library generations, but the requested cleanup removes the word
# from the deployable frontend too while preserving the behavior.

# workspace.ts: Professional Library record counter -> generation.
p = Path('src/workspace.ts')
s = p.read_text(encoding='utf-8')
s = s.replace('  revision: number;\n', '  generation: number;\n')
s = s.replace(
    '    revision: Number.isInteger(candidate.revision) && Number(candidate.revision) > 0 ? Number(candidate.revision) : 1,\n',
    '    generation: Number.isInteger(candidate.generation) && Number(candidate.generation) > 0 ? Number(candidate.generation) : 1,\n',
)
s = s.replace('.revision', '.generation')
s = s.replace(' revision:', ' generation:')
s = s.replace('CV revision', 'CV edit')
p.write_text(s, encoding='utf-8')

# ProfessionalLibrary.tsx: record counter + Spanish user-facing wording.
p = Path('src/ProfessionalLibrary.tsx')
s = p.read_text(encoding='utf-8')
s = s.replace('.revision', '.generation')
s = s.replace('revision:', 'generation:')
s = re.sub(r'revisi[oó]n', 'verificación', s, flags=re.I)
p.write_text(s, encoding='utf-8')

# Linked-library bookkeeping.
p = Path('src/libraryLinking.ts')
s = p.read_text(encoding='utf-8')
s = s.replace('appliedRevision', 'appliedGeneration')
s = s.replace('.revision', '.generation')
p.write_text(s, encoding='utf-8')

# React remount counter is merely a render key.
p = Path('src/main.tsx')
s = p.read_text(encoding='utf-8')
s = re.sub(r'\brevision\b', 'renderKey', s)
s = re.sub(r'\bsetRevision\b', 'setRenderKey', s)
p.write_text(s, encoding='utf-8')

# The old picker CSS is dead UI. Remove it rather than renaming it.
p = Path('src/styles.css')
s = p.read_text(encoding='utf-8')
s = re.sub(r'\.revisionPicker\{[^}]*\}\.revisionPicker label\{[^}]*\}\.revisionPicker button\{[^}]*\}', '', s)
s = re.sub(r'@media\(max-width:600px\)\{\.revisionPicker\{[^}]*\}\}', '', s)
p.write_text(s, encoding='utf-8')

# App/cloud/helper may contain leftover labels generated by older patches.
for name in ('src/App.tsx', 'src/cloud.ts', 'src/ec2-drive-migration-v154.ts'):
    p = Path(name)
    s = p.read_text(encoding='utf-8')
    s = re.sub(r'revisi[oó]n(?:es)?', 'copia', s, flags=re.I)
    s = re.sub(r'revisions?', 'copy', s, flags=re.I)
    p.write_text(s, encoding='utf-8')

# Fail at build time if the deployable frontend/backend still contains the word.
leftovers = []
for p in list(Path('src').rglob('*')) + [Path('server/app.py')]:
    if not p.is_file():
        continue
    try:
        text = p.read_text(encoding='utf-8')
    except UnicodeDecodeError:
        continue
    if re.search(r'revision|revisi[oó]n', text, flags=re.I):
        leftovers.append(str(p))
if leftovers:
    raise SystemExit('v1.6.2 purge: retired term remains in: ' + ', '.join(leftovers))

print('v1.6.2 purge applied: retired storage term removed from deployable frontend/backend identifiers and UI.')
